### ISSUE TITLE
Auto Groups 

### ISSUE THREAD

**Issue by KadeBehm** [AvolitesLtd/TitanManual#172]
**Link to the page in the manual:**
https://manual.avolites.com/docs/next/controlling-fixtures/fixture-groups/#auto-groups

**Old Text (if applicable):**
N/A 

**New Text:**
The "all" groups created automatically can not be deleted only unassigned to the show library. 

**Why it should be changed:**
Many do not understand that this is the case... or why it is ( I'm not even sure on the why myself ) I'm sure y text could be improved and should go in one of the blue info type boxes. 

**Other Information:**
Any other information

**Comment by congoblue** [comment]
I didn't know this but I am not sure whether it should be put in the manual, since the group does "appear" to be deleted although with a warning message.

Can anyone explain why it happens and if the user needs to know?

**Comment by p--b** [comment]
The groups need to exist because Titan keeps a special record of them so that it can update them if you patch fixtures in the future. In principle I suppose we could handle the case where the referenced fixture type group has gone away, but there would then be no way to recreate them once deleted unless we added that as extra functionality. Unassigning the group makes it "go away" from a user's perspective but means you can always get it back in future if you decide that you want the auto-group again. I would potentially be up for having some way of the user number being cleared in this case cause I always spend too much time renumbering all the autogroups... but that's a feature request :P

**Comment by KadeBehm** [comment]
This gives me enough explanation for the "Why" question to users now .. Thanks !
