### ISSUE TITLE
Add some information to the manual explaining that you need to run the synergy upgrade installer to run Synergy with AI

### ISSUE THREAD

**Issue by PeterBuddAvo** [AvolitesLtd/TitanManual#244]
https://manual.avolites.com/docs/synergy/setting-up/

This should mention pretty prominently that you need the correct version of the Synergy upgrade installer to run with Titan, though in principal you can run with any version of AI.

Maybe include a link to the download page.

**Comment by congoblue** [comment]
In what situation does the user need to run the upgrade installer? Does it get installed as part of a normal Titan upgrade?

**Comment by LawrenceGow** [comment]
Points I feel need to be made clear:
- The synergy upgrade installer is needed to update already existing versions of Ai so that they can communicate with new versions of Titan.
- It is not something that is done as part of upgrading Titan on a console/PC and is an extra step that needs to be taken.
- The upgrade installer does not need to be run for Titan installations.
- The upgrade installer needs to be run on Ai servers as it updates the dlls that makes synergy a thing.
