### ISSUE TITLE
Sections list hides grey navbar

### ISSUE THREAD

**Issue by marcheimendinger** [AvolitesLtd/TitanManual#70]
**Describe the bug**
When being on a page and clicking on the grey navbar top left three dot, a sections list appears but this makes the grey navbar to hide. It should stays in place in my opinion.

**To Reproduce**
1. Go to any page of the manual.
2. Click on the three dots on the grey navbar.
3. See that the grey navbar disappears.

**Expected behavior**
The grey navbar should still be there to allow user to hide the sections list again.

**Screenshots**
![image](https://user-images.githubusercontent.com/43568598/89063468-89317200-d368-11ea-8911-d7e3df8d7943.png)

![image](https://user-images.githubusercontent.com/43568598/89063479-90588000-d368-11ea-9afd-a01ca6698899.png)

**Smartphone (please complete the following information):**
 - Device: iPhone XS
 - OS: iOS 13.6
 - Browser: Safari

**Comment by garethnunns** [comment]
Hi @marcheimendinger,

Below is the expected behaviour:

![IMG_2725](https://user-images.githubusercontent.com/2584408/89081910-66ad5200-d384-11ea-8ffd-d35ea010f50e.PNG) | ![IMG_2726](https://user-images.githubusercontent.com/2584408/89081913-69a84280-d384-11ea-9ff8-4a2adac54e5f.PNG)
---|---
*Step 1*|*Step 2*

This is working fine for me on:
- Device: iPhone 6S
- OS: iOS 13.5.1
- Browser: Safari

Could you try [clearing cache](https://support.apple.com/en-gb/HT201265) or try using private browsing to confirm it's not a local issue

**Comment by marcheimendinger** [comment]
Hi @garethnunns,

In fact this is working after clearing the cache.

Thanks!
